code/_globalvars/lists/flavor_misc.dm
What this PR does is basically makes the backpack selectable via the backpack menu.
This PR is a port from this server, https://github.com/ARF-SS13/coyote-bayou/pull/504
:cl:
add: backpack to backpain menu in a way.
/:cl:
=> Port: Backpack selection gets slightly bigger.

code/modules/projectiles/projectile/special/rocket.dm
Someone brought it to my attention that  high-yield rockets were statistically superior to the 40mm GL, which no longer comes free with the Prime Decanus. In order to maintain balance, and because I know that rockets in their current state would be less fun to fight than the 40mm, I am nerfing the shrapnel factor heavily to make it less crippling.
High-Yield rockets already have a higher explosive effect than 40mm HE, so the literally quadrupled shrapnel factor that the rocket had has been cut from 24 to 3. Low-yield now does shrapnel factor of 6 compared to 12, making it still useful as a fragmentation rocket due to its smaller blast radius, but now it isn't basically guaranteed to one-shot anyone within a country mile of it.
:cl:
balance: Low-Yield Rocket shrapnel factor reduced to 6 …
=> Rocket balance pass

code/modules/jobs/job_types/followers.dm
That's it, that's all it does.
Adds a pip to the FoA Admin role.
FoA Admin is a leadership role, most leadership roles spawn with pips- that and over half of the loadouts for every other follower role spawns with a pip. There's seemingly no reason as to why they shouldn't get one as well.
:cl:
add: Pip to the FoA Admin Loadout
/:cl:
=> FoA Admin Pip

_maps/map_files/Pahrump-Sunset/Pahrump-Sunset.dmm
Fixes the Khan anvil being debug.
This is Bad: 
:cl:
tweak: Makes the anvil a proper anvil
/:cl:
=> Khan Anvil Fix

code/game/objects/items/defib.dm, code/game/objects/items/fallout13misc.dm, code/game/objects/items/storage/backpack.dm
adds defib to surgery kits, removes brain damage from being revived (no more defib trauma)
:cl:
code: defibs are now in surgery kits
code: defibs should no longer cause brain traumas
code: flag poles can now be walked past
/:cl:
=> adds defib to surgery kits, removes brain damage from being revived (no more defib trauma)

code/game/machinery/autolathe.dm, code/modules/fallout/machinery/alchemy_table.dm, code/modules/hydroponics/biogenerator.dm, code/modules/hydroponics/gene_modder.dm, code/modules/hydroponics/hydroponics.dm, code/modules/hydroponics/seed_extractor.dm
Back on Sunset, having the Technophreak trait used to allow you to use things like autolathes and botany machines even if you were a tribal or a former tribal. In fact, there was a Tribal loadout or two that were specifically designed with this in mind.
Being a Former Tribal does not actually give you any tribal recipes to speak of, it just lets you benefit better from tribal medicine. Former Tribal should also have allowed you to use the primitive chemistry set, which functions more or less like a chem master, and it does now.
:cl:
balance: Technophreak trait once again allows the use of certain machines that are normally locked by the Technophobe trait.
balance: Having the Technophobe trait (such as from Former Tribal) allows you to use the primitive chemistry bench (tribal chem …
=> Un-nerfs Dean's Electronics & Former Tribal

code/modules/food_and_drinks/recipes/drinks_recipes.dm
Ever wanted to make your own Sarsaparilla using freshly farmed ingredients? Well now you can! Using equal parts vanilla, caramel, and Xander root juice, you can mix your own homemade version of the best drink in the Wasteland!
Basically lets you make Sunset Sarsaparilla from sugar cane, Xander root, and vanilla beans, with a little processing.
:cl:
add: You can now mix your own Sunset Sarsaparilla with equal parts xander juice, caramel, and vanilla.
/:cl:
=> Adds a recipe for sunset sarsaparilla

code/datums/wounds/slash.dm, code/game/objects/items/stacks/medical.dm, code/game/objects/items/storage/survivalkit.dm, code/modules/mob/living/blood.dm, code/modules/mob/living/carbon/carbon.dm
makes bloodloss more severe if left untreated, as well as adding a trail of blood for those that are bleeding. this ports some of the blood code from upstream TG, as well as some wasteland-specific edits to wound severity.
it'll also add a suture as basekit for the survival kits
:cl:
refactor: reworked bloodloss and wound severity
/:cl:
=> wounds rework

code/game/objects/items/defib.dm, code/game/objects/items/tanks/tank_types.dm
adds simple anesthesia without the use of atmos. click a player with an atmos tank in-hand to administer a dose
also removes unused variables in the defib file i forgor in a previous pr
:cl:
add: anesthesia without atmos
/:cl:
=> adds anesthesia without atmos

code/datums/wounds/slash.dm, code/game/objects/items/stacks/medical.dm, code/game/objects/items/storage/survivalkit.dm, code/modules/mob/living/blood.dm, code/modules/mob/living/carbon/carbon.dm
Reverts JasmineRickards/Wasteland-After-Dark#17
=> Revert "wounds rework"

code/game/objects/items/granters.dm, code/modules/jobs/job_types/legion.dm
https://github.com/sunset-wasteland/sunset-wasteland/pull/704
https://github.com/sunset-wasteland/sunset-wasteland/pull/710
- Orator loadouts
- Teachings of mars
=> Partially ports sunset PRs #704 and #710 - Legion Priestess

code/datums/diseases/f13_fev.dm, code/datums/traits/neutral.dm
:cl:
Fix: Correctly adjusts character bodysize.
Fix: Instant stage 4 on all FEV
/:cl:
=> FEV Fix (Bodysize)

code/modules/reagents/chemistry/reagents/toxin_reagents.dm
:cl:
tweak: Mutagen -> DFEV
/:cl:
=> <REFLUFF> Mutagen -> Diluted Forced Evolutionary Virus

code/modules/reagents/chemistry/machinery/chem_dispenser.dm
Host request, adds fusion core based dispensers to the game.
Allows for industrial dispensers/etc to be very easily balanced around needing fusion cores.
:cl:
add: FC infrastructure!
/:cl:
=> Fusion Core Dispensers

code/modules/reagents/chemistry/machinery/chem_dispenser.dm
=> waaaaaaaaaa

code/datums/traits/good.dm, code/game/objects/items/melee/f13onehanded.dm
:cl:
Fix: Fixes the pugilist trait and one-handed weapon from softlocking you. Or stacking infinite damage.
/:cl:
=> <I AM GOING TO BEAT AND KILL EVERY FALLOUT CODER> Fixes one-handed gauntlet weapons.

modular_citadel/code/modules/client/loadout/head.dm, modular_citadel/code/modules/client/loadout/shoes.dm, modular_citadel/code/modules/client/loadout/uniform.dm
What this PR does is finally fixes the khan loadouts instead of having to buy it for like ten caps and then waste caps.
:cl:
tweak: loadout code
/:cl:
=> Khan Bug Fix: Loadout 

_maps/map_files/Pahrump-Sunset/Pahrump-Sunset-Lower.dmm, _maps/map_files/Pahrump-Sunset/Pahrump-Sunset-Upper.dmm, _maps/map_files/Pahrump-Sunset/Pahrump-Sunset.dmm
Yeah I didn't know Yawet made mapping PRs.
Readds the things that should have been there in the first place. My bad
:cl:
fix: Readds the overwritten machinery items.
/:cl:
=> Fixes Mapping Overwrites

_maps/map_files/Pahrump-Sunset/Pahrump-Sunset-Upper.dmm, _maps/map_files/Pahrump-Sunset/Pahrump-Sunset.dmm
Readds DumDum's Khan area that got overwritten from a previous pull.
It was supposed to be there. It /should/ be fixed. Needs a look over.
:cl:
tweak: The maps so they aren't the overwritten maps.
/:cl:
=> Readds the Khan Base & Adds space tiles for stairs on the surface BoS Area

code/game/objects/items/mop.dm
=> webedit to make mops work with dirty water

code/modules/fallout/reagents/medicines.dm
Fixes the thing making combat stims so fucking overpowered and insane, same with tribal meds.
IF ONLY YOU KNEW HOW BAD IT WAS
:cl:
fix: Unintentional superhealing on tribal meds/stimpacks.
add: Blood clotting effects on tribal meds/stimpacks
del: Stupid fucking code that was running on mob/living instead of mob/living/carbon
/:cl:
=> MASSIVE Fallout Med Bugfix || Stimpack/Tribal med Nerf + Fix

code/datums/diseases/f13_fev.dm, code/modules/fallout/reagents/medicines.dm, code/modules/hydroponics/grown/punga.dm
:cl:
add: Curling stage 6
add: Pungafruit mutadone
del: 3 requirements for curling
tweak: Curling cure requirements
tweak: Curling rad amounts (Subject to change)
fix: FEV-II cures and text
del: Poopy things that broke the game
add: Host Request: Weaker stimpack healing for synths
/:cl:
=> FEV Changes, Nerfs & Buffs

code/modules/power/antimatter/control.dm
wah
weh
:cl:
Add: Overload mechanics to AM reactor
Del: Griefability
/:cl:
=> <Antigrief/Raid Mechanics> Antimatter Control changes

code/modules/jobs/job_types/enclave.dm
Yeah so Enclave Private used to be 3500 job xp for some reason so I've fixed that and made it 850. This applies to other jobs too.
Allows people to play Enclave more to stress test Enclave "doing more stuff."
:cl:
Tweak: job xp for Enclave
/:cl:
=> EnclaveXPReduction

code/modules/jobs/job_types/wasteland.dm
Adds more outlaw slots cause we got like 100 people last night lol.
More outlaws is a net gain.
:cl:
add: outlaw slots
/:cl:
=> Adds more outlaw slots

code/modules/jobs/job_types/bos.dm, code/modules/projectiles/guns/ballistic/automatic.dm
=> M60 HOTFIX

code/game/objects/items/melee/f13onehanded.dm, code/modules/mob/living/carbon/human/species.dm
:cl:
fix: Hopefully finally kills punch damage bugs involving glove melee
/:cl:
=> <QWIKFIX> Species.DM/one hand fix

code/modules/clothing/suits/f13armor.dm, code/modules/clothing/suits/heavy_armor.dm, code/modules/reagents/chemistry/reagents/toxin_reagents.dm
:cl:
add: New variables for PA
fix: Getting shrapnel/slipped through PA
tweak: Adds pushimmune to SPA
admin: Adds tweakable variable to PA to allow for god-sets.
/:cl:
=> <Host Request> PA Tweaks

code/modules/clothing/suits/heavy_armor.dm
:cl:
add: Added new things
add: Added more things
del: Removed old things
tweak: tweaked a few things
balance: rebalanced something
fix: fixed a few things
soundadd: added a new sound thingy
sounddel: removed an old sound thingy
imageadd: added some icons and images
imagedel: deleted some icons and images
spellcheck: fixed a few typos
code: changed some code
refactor: refactored some code
config: changed some config setting
admin: messed with admin stuff
server: something server ops should know
/:cl:
=> fuckfuckfcuk

code/modules/jobs/job_types/ncr.dm
:cl:
add: NCR LT Sniper/PA Choice
/:cl:
=> <HOST REQUEST> NCR new LT loadouts

code/modules/jobs/job_types/ncr.dm
=> Loadout Fix

code/datums/components/crafting/recipes/recipes_misc.dm, code/modules/jobs/access.dm, code/modules/jobs/job_types/bos_civilian.dm, code/modules/jobs/job_types/ncr.dm, code/modules/jobs/jobs.dm
:cl:
add: Protectorate in its entirety
del: shitcode
fix: shitcode
/:cl:
=> Protectorate real

code/__DEFINES/reagents.dm, code/modules/research/designs/biogenerator_designs.dm
:cl:
add: Strange seeds to biogen
del: Stupid shit
/:cl:
=> Strange Seeds in Fertile Flowerpots.

code/modules/jobs/job_types/ncr.dm
:cl:
fix: Loadout code (hopefully)
/:cl:
=> <PA FIX> NCR fixes

code/modules/mob/living/carbon/human/species_types/supermutant.dm
:cl:
add: Added new things
add: Added more things
del: Removed old things
tweak: tweaked a few things
balance: rebalanced something
fix: fixed a few things
soundadd: added a new sound thingy
sounddel: removed an old sound thingy
imageadd: added some icons and images
imagedel: deleted some icons and images
spellcheck: fixed a few typos
code: changed some code
refactor: refactored some code
config: changed some config setting
admin: messed with admin stuff
server: something server ops should know
/:cl:
=> Atmos fix for supermutants

code/game/objects/items/stacks/sheets/sheet_types.dm, code/modules/jobs/job_types/enclave.dm, code/modules/research/techweb/_techweb.dm, code/modules/research/techweb/nodes/faction_nodes.dm, code/modules/research/techweb/nodes/mecha_nodes.dm, fortune13.dme
:cl:
add: Faction tech support
del: Combat mechs for followers
add: X-05 H(eavy)P(ower)A(rmor) (Enclave)
add: CQC Operator (Enclave)
fix: Enclave armory access & Cham masks
add: Pre-war component printing
fix: Pre-war alloys being useless
del: H(eavy)P(pulse)R(ifles) for all factions
tweak: Enclave flavor text
/:cl:
=> New Faction Techs, fixes, nerfs.

code/modules/research/designs/weapon_designs.dm, code/modules/research/techweb/_techweb.dm, code/modules/research/techweb/nodes/faction_nodes.dm, code/modules/research/techweb/nodes/mecha_nodes.dm
:cl:
fix: Forgot to push a change, fixed now
/:cl:
=> <QWIKFIX> Fixes techweb bug

code/modules/research/techweb/nodes/faction_nodes.dm
:cl:
fix: Prevents Enclave from magically framing BoS with a clone army + printed mechs
/:cl:
=> A slight oopsiedaisy, fixed.

code/modules/projectiles/gun.dm
From where you're kneeling it must seem like an 18-carat run of bad luck...
-It takes 4 uninterrupted seconds to begin an execution (Help intent mouth)
-Reflavored to have Fallout: NV referenced descriptions
=> You've made your last delivery, kid.

code/modules/projectiles/guns/ballistic/rifle.dm
Spread is now 2, from 4
Melee damage is now 20, from 5
Slowdown is now 0.4, from 0.5
Penetration debuff is now -35, from -40
=> Tweaks sawn-off AMR according to in-round feedback

code/modules/research/techweb/nodes/medical_nodes.dm
Reintroducing the Defib Upgrade notes that for some reason got removed a while ago. This should be a slight comvienient upgrades given you have the tools for.
Allow Follower to enjoy not burning themselves after reviving a guy. Slight convenient Upgrades
:cl:
add:Re-introducing the Defib Upgrade
/:cl:
=> Re-introduce the defib upgrades from the RnD Machine

code/modules/mob/say_vr.dm
Reverts JasmineRickards/Wasteland-After-Dark#134 Broken PR
code\modules\mob\say_vr.dm:68:error: LOG_SUBTLE: undefined var
code\modules\mob\say_vr.dm:69:error: user.say_narrate_replace: undefined proc
=> Revert "Fixes Anti-Ghost (ERP-Flashbangs-B-Gone)"

code/modules/jobs/job_types/legion.dm, code/modules/projectiles/boxes_magazines/internal/rifle.dm, code/modules/projectiles/boxes_magazines/internal/shotgun.dm, code/modules/projectiles/guns/ballistic/automatic.dm, code/modules/projectiles/guns/ballistic/rifle.dm
Tweaks the Assultus, making it terribly innacurate and makes it use an non-detachable refillable magazine as it was originaly intended.
:cl:
tweak: made the assultus spread a lot worse
fix: fixed the assultus magazine
/:cl:
=> Assultus fix

code/modules/research/techweb/nodes/medical_nodes.dm, code/modules/research/techweb/nodes/weaponry_nodes.dm
Re-introduce the defib upgrades
so followers won't fry their own hands off trying to revive people with the given tool
:cl:
add: re-introduce the adv-defib
/:cl:
=> Defib Upgrade

code/modules/mob/say_vr.dm
Reverts JasmineRickards/Wasteland-After-Dark#140 Still doesn't work.
=> Revert "Attempt 2 at fixing the mess known as subtler anti-ghost"

code/modules/projectiles/guns/ballistic/rifle.dm
I fucked up and messed up the assultus auto rack code line.  This fixes it, making it work as intended.
=> Assultus hotfix
